// SEZIONE 14, LEZIONE 68 - CORSO UDEMY JS
// METODI DELL'OGGETTO ARRAY IN JAVASCRIPT
// I metodi some() e every() di un array:

// SOME METHOD: RETURNS TRUE IF THERE IS ALMOST ONE ELEMENT THAT VERIFY THE CALLBACK

// EVERY METHOD: RETURNS TRUE IF ALL ELEMENTS VERIFY THE CALLBACK

